# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_key import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities = pd.read_csv("../output_data/city.csv")

In [3]:
#My cities into a dataframe
cities_df = pd.DataFrame(cities)
cities_df

,Unnamed: 0,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
0,0,Riviere-au-Renard,49.00,-64.40,282.15,49,5,2.60,CA,1603031284
1,1,Georgiyevskoye,58.73,45.02,276.98,94,100,4.75,RU,1603031285
2,2,Norman Wells,65.28,-126.83,260.15,84,20,2.60,CA,1603030993
3,3,Lompoc,34.64,-120.46,284.15,87,1,2.17,US,1603031287
4,4,East London,-33.02,27.91,292.15,72,13,8.20,ZA,1603031033
...,...,...,...,...,...,...,...,...,...,...
562,562,Isla Vista,34.41,-119.86,286.15,93,90,1.23,US,1603031888
563,563,Departamento de Maldonado,-34.67,-54.92,300.15,57,20,3.10,UY,1603031889
564,564,Chak Thirty-one -Eleven Left,30.43,72.70,297.95,17,0,1.06,PK,1603031891
565,565,Kulu,39.10,33.08,293.33,38,97,1.22,TR,1603031892
566,566,Grindavik,63.84,-22.43,279.15,87,75,7.20,IS,1603031893

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
#Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [5]:
#Store 'Lat' and 'Lng' into  locations 
locations = cities_df[["lat", "lng"]].astype(float)

#Converting Humidity to a float for weight on heatmap
humidity = cities_df["humidity"].astype(float)

In [7]:
#Creating humidity heat map
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                dissipating=False,
                                max_intensity=100,
                                point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [8]:
#My ideal weather 
my_cities = cities_df.loc[(cities_df["max_temp"]<288)&
                          (cities_df["max_temp"]>210)&
                          (cities_df["humidity"]>50)&
                          (cities_df["cloudiness"]<60)&
                          (cities_df["cloudiness"]>30)&
                          (cities_df["wind_speed"]<8)]
my_cities = my_cities.dropna()
my_cities_df = pd.DataFrame(my_cities)
my_cities_df

,Unnamed: 0,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date
32,32,Punta Arenas,-53.15,-70.92,279.15,81,40,7.70,CL,1603030903
56,56,Hasaki,35.73,140.83,287.15,87,40,5.70,JP,1603031343
106,106,Longyearbyen,78.22,15.64,271.15,74,40,5.70,SJ,1603030899
136,136,AsÄƒu,46.43,26.40,284.26,71,35,1.53,RO,1603031430
159,159,BerlevÃ¥g,70.86,29.09,275.91,80,45,2.03,NO,1603030966
166,166,Ngunguru,-35.62,174.50,284.26,91,38,0.45,NZ,1603031462
192,192,Nome,64.50,-165.41,277.15,86,40,5.10,US,1603031490
217,217,Kirkwall,58.98,-2.96,280.15,81,40,1.00,GB,1603031517
218,218,Nadym,65.53,72.52,269.40,96,54,6.75,RU,1603031518
220,220,Severo-Kuril'sk,50.68,156.12,280.64,82,50,4.72,RU,1603030937
233,233,VardÃ¸,70.37,31.11,271.15,86,40,3.60,NO,1603030958
291,291,Fortuna,40.60,-124.16,282.15,100,40,3.60,US,1603031101
306,306,Mount Gambier,-37.83,140.77,281.15,93,40,2.60,AU,1603031133
348,348,Kabansk,52.05,106.65,274.15,74,47,3.00,RU,1603031657
388,388,SÃ¦by,57.33,10.52,283.15,59,41,1.34,DK,1603031700
396,396,Amga,60.90,131.96,260.60,95,47,1.44,RU,1603031709
404,404,Yuzhnyy,53.25,83.69,274.15,59,45,6.00,RU,1603031718
405,405,Jumla,29.27,82.18,285.40,66,57,1.30,NP,1603031719
412,412,Bukachacha,52.98,116.92,271.97,95,51,0.80,RU,1603031726
416,416,Coihueco,-36.62,-71.83,285.15,81,40,3.10,CL,1603031731
451,451,Mokhsogollokh,61.47,128.92,261.86,96,58,2.09,RU,1603031768
456,456,Ballybofey,54.80,-7.78,287.15,71,33,4.60,IE,1603031774
477,477,ShingÅ«,33.73,135.98,287.70,81,51,2.53,JP,1603031198
485,485,Ust'-Ishim,57.69,71.17,272.39,95,40,2.99,RU,1603031805
540,540,Narsaq,60.92,-46.05,277.15,85,38,1.50,GL,1603031865

In [9]:
#Cleaning the my cities df
my_cities_df = my_cities_df[['city',
                            'lat',
                            'lng',
                            'max_temp',
                            'humidity',
                            'cloudiness',
                            'wind_speed',
                            'country']]

my_cities_df = my_cities_df.reset_index(drop=True)
my_cities_df

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country
0,Punta Arenas,-53.15,-70.92,279.15,81,40,7.70,CL
1,Hasaki,35.73,140.83,287.15,87,40,5.70,JP
2,Longyearbyen,78.22,15.64,271.15,74,40,5.70,SJ
3,AsÄƒu,46.43,26.40,284.26,71,35,1.53,RO
4,BerlevÃ¥g,70.86,29.09,275.91,80,45,2.03,NO
5,Ngunguru,-35.62,174.50,284.26,91,38,0.45,NZ
6,Nome,64.50,-165.41,277.15,86,40,5.10,US
7,Kirkwall,58.98,-2.96,280.15,81,40,1.00,GB
8,Nadym,65.53,72.52,269.40,96,54,6.75,RU
9,Severo-Kuril'sk,50.68,156.12,280.64,82,50,4.72,RU
10,VardÃ¸,70.37,31.11,271.15,86,40,3.60,NO
11,Fortuna,40.60,-124.16,282.15,100,40,3.60,US
12,Mount Gambier,-37.83,140.77,281.15,93,40,2.60,AU
13,Kabansk,52.05,106.65,274.15,74,47,3.00,RU
14,SÃ¦by,57.33,10.52,283.15,59,41,1.34,DK
15,Amga,60.90,131.96,260.60,95,47,1.44,RU
16,Yuzhnyy,53.25,83.69,274.15,59,45,6.00,RU
17,Jumla,29.27,82.18,285.40,66,57,1.30,NP
18,Bukachacha,52.98,116.92,271.97,95,51,0.80,RU
19,Coihueco,-36.62,-71.83,285.15,81,40,3.10,CL
20,Mokhsogollokh,61.47,128.92,261.86,96,58,2.09,RU
21,Ballybofey,54.80,-7.78,287.15,71,33,4.60,IE
22,ShingÅ«,33.73,135.98,287.70,81,51,2.53,JP
23,Ust'-Ishim,57.69,71.17,272.39,95,40,2.99,RU
24,Narsaq,60.92,-46.05,277.15,85,38,1.50,GL

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
#Changing variable for hotel map
hotel_df = my_cities_df
hotel_df

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country
0,Punta Arenas,-53.15,-70.92,279.15,81,40,7.70,CL
1,Hasaki,35.73,140.83,287.15,87,40,5.70,JP
2,Longyearbyen,78.22,15.64,271.15,74,40,5.70,SJ
3,AsÄƒu,46.43,26.40,284.26,71,35,1.53,RO
4,BerlevÃ¥g,70.86,29.09,275.91,80,45,2.03,NO
5,Ngunguru,-35.62,174.50,284.26,91,38,0.45,NZ
6,Nome,64.50,-165.41,277.15,86,40,5.10,US
7,Kirkwall,58.98,-2.96,280.15,81,40,1.00,GB
8,Nadym,65.53,72.52,269.40,96,54,6.75,RU
9,Severo-Kuril'sk,50.68,156.12,280.64,82,50,4.72,RU
10,VardÃ¸,70.37,31.11,271.15,86,40,3.60,NO
11,Fortuna,40.60,-124.16,282.15,100,40,3.60,US
12,Mount Gambier,-37.83,140.77,281.15,93,40,2.60,AU
13,Kabansk,52.05,106.65,274.15,74,47,3.00,RU
14,SÃ¦by,57.33,10.52,283.15,59,41,1.34,DK
15,Amga,60.90,131.96,260.60,95,47,1.44,RU
16,Yuzhnyy,53.25,83.69,274.15,59,45,6.00,RU
17,Jumla,29.27,82.18,285.40,66,57,1.30,NP
18,Bukachacha,52.98,116.92,271.97,95,51,0.80,RU
19,Coihueco,-36.62,-71.83,285.15,81,40,3.10,CL
20,Mokhsogollokh,61.47,128.92,261.86,96,58,2.09,RU
21,Ballybofey,54.80,-7.78,287.15,71,33,4.60,IE
22,ShingÅ«,33.73,135.98,287.70,81,51,2.53,JP
23,Ust'-Ishim,57.69,71.17,272.39,95,40,2.99,RU
24,Narsaq,60.92,-46.05,277.15,85,38,1.50,GL

In [11]:
#Adding hotel column to hotel_df

hotel_df['hotel_name']=""
hotel_df

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,hotel_name
0,Punta Arenas,-53.15,-70.92,279.15,81,40,7.70,CL,
1,Hasaki,35.73,140.83,287.15,87,40,5.70,JP,
2,Longyearbyen,78.22,15.64,271.15,74,40,5.70,SJ,
3,AsÄƒu,46.43,26.40,284.26,71,35,1.53,RO,
4,BerlevÃ¥g,70.86,29.09,275.91,80,45,2.03,NO,
5,Ngunguru,-35.62,174.50,284.26,91,38,0.45,NZ,
6,Nome,64.50,-165.41,277.15,86,40,5.10,US,
7,Kirkwall,58.98,-2.96,280.15,81,40,1.00,GB,
8,Nadym,65.53,72.52,269.40,96,54,6.75,RU,
9,Severo-Kuril'sk,50.68,156.12,280.64,82,50,4.72,RU,
10,VardÃ¸,70.37,31.11,271.15,86,40,3.60,NO,
11,Fortuna,40.60,-124.16,282.15,100,40,3.60,US,
12,Mount Gambier,-37.83,140.77,281.15,93,40,2.60,AU,
13,Kabansk,52.05,106.65,274.15,74,47,3.00,RU,
14,SÃ¦by,57.33,10.52,283.15,59,41,1.34,DK,
15,Amga,60.90,131.96,260.60,95,47,1.44,RU,
16,Yuzhnyy,53.25,83.69,274.15,59,45,6.00,RU,
17,Jumla,29.27,82.18,285.40,66,57,1.30,NP,
18,Bukachacha,52.98,116.92,271.97,95,51,0.80,RU,
19,Coihueco,-36.62,-71.83,285.15,81,40,3.10,CL,
20,Mokhsogollokh,61.47,128.92,261.86,96,58,2.09,RU,
21,Ballybofey,54.80,-7.78,287.15,71,33,4.60,IE,
22,ShingÅ«,33.73,135.98,287.70,81,51,2.53,JP,
23,Ust'-Ishim,57.69,71.17,272.39,95,40,2.99,RU,
24,Narsaq,60.92,-46.05,277.15,85,38,1.50,GL,

In [12]:
#Setting the parameters for the hotels and the loop through hotel_df for coordinates

params = {
    "radius":"5000",
    "types":"lodging",
    "key":g_key,
}

for index, row in hotel_df.iterrows():
    
    #get lat and lng for df
    lat = row['lat']
    lng = row['lng']
    
    #Changing the location with each iteration
    params["location"] = f"{lat},{lng}"
    
    #searching for the hotel by lat and lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    #make request and print url 
    hotel_names = requests.get(base_url, params=params)
    
    #covert to json
    hotel_names = hotel_names.json()
    
    #adding to the hotel_df
    try:
        hotel_df.loc[index,"hotel_name"] = hotel_names["results"][0]['name']
    except (KeyError, IndexError):
        print("Missing.&.skip")

Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip
Missing.&.skip

In [13]:
hotel_df = pd.DataFrame(hotel_df)
hotel_df

,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,hotel_name
0,Punta Arenas,-53.15,-70.92,279.15,81,40,7.70,CL,
1,Hasaki,35.73,140.83,287.15,87,40,5.70,JP,
2,Longyearbyen,78.22,15.64,271.15,74,40,5.70,SJ,
3,AsÄƒu,46.43,26.40,284.26,71,35,1.53,RO,
4,BerlevÃ¥g,70.86,29.09,275.91,80,45,2.03,NO,
5,Ngunguru,-35.62,174.50,284.26,91,38,0.45,NZ,
6,Nome,64.50,-165.41,277.15,86,40,5.10,US,
7,Kirkwall,58.98,-2.96,280.15,81,40,1.00,GB,
8,Nadym,65.53,72.52,269.40,96,54,6.75,RU,
9,Severo-Kuril'sk,50.68,156.12,280.64,82,50,4.72,RU,
10,VardÃ¸,70.37,31.11,271.15,86,40,3.60,NO,
11,Fortuna,40.60,-124.16,282.15,100,40,3.60,US,
12,Mount Gambier,-37.83,140.77,281.15,93,40,2.60,AU,
13,Kabansk,52.05,106.65,274.15,74,47,3.00,RU,
14,SÃ¦by,57.33,10.52,283.15,59,41,1.34,DK,
15,Amga,60.90,131.96,260.60,95,47,1.44,RU,
16,Yuzhnyy,53.25,83.69,274.15,59,45,6.00,RU,
17,Jumla,29.27,82.18,285.40,66,57,1.30,NP,
18,Bukachacha,52.98,116.92,271.97,95,51,0.80,RU,
19,Coihueco,-36.62,-71.83,285.15,81,40,3.10,CL,
20,Mokhsogollokh,61.47,128.92,261.86,96,58,2.09,RU,
21,Ballybofey,54.80,-7.78,287.15,71,33,4.60,IE,
22,ShingÅ«,33.73,135.98,287.70,81,51,2.53,JP,
23,Ust'-Ishim,57.69,71.17,272.39,95,40,2.99,RU,
24,Narsaq,60.92,-46.05,277.15,85,38,1.50,GL,

In [14]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{hotel_name}</dd>
<dt>City</dt><dd>{city}</dd>
<dt>Country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
Locations = hotel_df[["lat", "lng"]]

In [17]:
hotel_layer = gmaps.symbol_layer(Locations, 
                                 fill_color='rgba(0, 150, 0, 0.4)',
                                 stroke_color='rgba(0, 0, 150, 0.4)', scale=10,
                                 info_box_content=[f'{row}' for index, row in hotel_df.iterrows()])

In [18]:
# Add marker layer ontop of heat map
fig = gmaps.figure()

fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)


# Display figure
fig

Figure(layout=FigureLayout(height='420px'))